[passwords]
# Follow the rule: username = "password"
Alireza_Jafari_Admin_AJF_22-adminPanel = "alireza1381jafariA8J1FdaneshgaheAzadVahedeElecteroniki1381191"
Ostad_Nilofare_Mirzaii_Admin_-adminPanel = "OstaddoctorNilofareMirzaii13O1N3MOsTaDeDaneshGaheAzaDeVahedeKaraJ1310#"
MohamMad_AmiN_Admin_NeWADMIN_23-adminPanel = "MohamMadAmiNe1380M1A3m8N0DaneShGahEAzaDevAHeDeKRAJ13020#$DaneshJoYeComPuTeR"